apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aduke
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/GreatOmotayo/azure-aks-container-platform.git
    targetRevision: main
    path: charts/aduke
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true