{{- if .Values.appInsights.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aduke-app-insights-spc
  namespace: app
spec:
  provider: azure
  parameters: 
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: {{ .Values.global.grafanaIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.keyVaultTenantId | quote }}
    objects: |
      array:
        - |
          objectName: aduke-app-insights-connection-string
          objectType: secret
  secretObjects:
    - secretName: aduke-app-insights-credentials
      type: Opaque
      data:
        - objectName: aduke-app-insights-connection-string
          key: connection-string
{{- end }}
