apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: worker-spc
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.keyVault.secretName }}
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storageAccountName
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.serviceAccount.azureClientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.azureTenantId | quote }}
    objects: |
      array:
        - |
          objectName: storage-account-name
          objectType: secret