replicaCount: 2
image:
  repository: "omotayoaksregistry.azurecr.io/aduke"
  tag: "46fab640ebb64f1a08a8a63da4965923be6af310"
  pullPolicy: IfNotPresent
serviceAccount:
  name: aduke
  azureClientId: "671704e4-d227-4b4c-81f9-05d4483e121f"
service:
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
ingress:
  enabled: true
  className: nginx
  host: aduke.local
  path: /
keyVault:
  secretName: aduke-storage-config
  vaultUri: "https://omotayo-aks-kv.vault.azure.net/"
  name: "omotayo-aks-kv"
azureTenantId: "175d86cd-6e18-4ee9-84a6-c6b0d003ecc9"
networkPolicy:
  ingressControllerNamespace: ingress-nginx
  privateEndpointSubnetCidr: "10.1.1.0/24"
